### ISSUE TITLE
error while parsing $upstream_response_time: value '-' could not be parsed into float

### ISSUE THREAD

**Issue by lhanjian** [martin-helmich/prometheus-nginxlog-exporter#224]
**Describe the bug**

error while parsing $upstream_response_time: value '-' could not be parsed into float

**Root cause(?)**

https://github.com/martin-helmich/prometheus-nginxlog-exporter/pull/221/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R453

**Comment by lhanjian** [comment]
nginx variables use "-" to represent empty.

**Comment by lhanjian** [comment]
$upstream_response_time either a number or unset. Nginx logs unset variables as dash (-)



https://stackoverflow.com/questions/36788856/nginx-log-filter-upstream-response-time-json-elk-parsefailure

**Comment by lhanjian** [comment]
it may be "502, -, 502" or "-"

**Comment by martin-helmich** [comment]
Yes, this was introduced as a side effect of #221 -- this should not affect metrics generation, since the error is only logged (meaning the actual metrics should be provided just the same as before). However, I do get that the logs are annoying and should not increase the `parse_error_count` metric. Will fix shortly.
