### ISSUE TITLE
Keep a checkpoint of the last known log location

### ISSUE THREAD

**Issue by pgporada** [martin-helmich/prometheus-nginxlog-exporter#81]
**Issue type**:
Feature request  

**What happened**:
A particular server produces many GB of log a day. When I need to troubleshoot an issue by enabling an extra nginx field, the exporter will have to receive an updated config and subsequently be restarted. Due to the restart, the exporter re-parses the entire log file from the beginning to "now" which causes it to throw errors because the beginning of the file doesn't match the live config in the exporter. The result of this is missing metrics until the exporter catches up to "now". Sometimes this re-parsing can take upwards of an hour.

**What you expected to happen**:
I expect the nginx exporter to pick up where it left off after the exporter gets restarted instead of having to re-scan the entire log file.

**Environment**:
- Exporter version: https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/tag/v1.3.0
- OS (e.g. from /etc/os-release): CentOS 7

Thank you for this tool, it's been very helpful thus far.

**Comment by pgporada** [comment]
Issue https://github.com/martin-helmich/prometheus-nginxlog-exporter/issues/73 seems to be relevant as well.

**Comment by martin-helmich** [comment]
Sorry for the late response!

>Due to the restart, the exporter re-parses the entire log file from the beginning to "now" which causes it to throw errors

This shouldn't happen at all since the exporter should only start reading the access log from the end of the file, anyway. Are you absolutely sure that's what is happening here?

Apart from this, a checkpointing feature sounds like it might be a useful alternative to the "read file from its end" approach. I cannot make any promises as to if and when I'll find the time for building this, though. Pull requests are always welcome, however.

For a complete implementation of this, the exporter would have to know where to store its state (probably a file at a configurable location) and would need to be able to handle if a log file is rotated while the exporter is down.

**Comment by pgporada** [comment]
Bump to keep this open

**Comment by martin-helmich** [comment]
Sorry for the accidental close, @pgporada. Seems like @helmich-bot got a bit overzealous on this one.
