### ISSUE TITLE
JSON File Support

### ISSUE THREAD

**Issue by kadaan** [martin-helmich/prometheus-nginxlog-exporter#93]
**Issue type**:
Feature request  

I'd like to add support for JSON log files.  What are your feelings about this?

**Comment by kadaan** [comment]
@martin-helmich What do you think?

**Comment by martin-helmich** [comment]
Hey @kadaan, sorry for the late response! I would most certainly be willing to accept PRs for this. :+1:

However, I fear that some refactoring might be necessary beforehand; basically we'd need to replace most usages of `*gonx.Parser` (which is what does the actual line-by-line-parsing at the moment) with a more generic interface (which might then be implemented by a `gonx`-backed parser, or a JSON parser).

**Comment by brandery** [comment]
how about separate the consul's config to a standalone file? which I mean is that as consul's registration support http with json format, and don't need to do some stuff  in this project again......

**Comment by martin-helmich** [comment]
>how about separate the consul's config to a standalone file? which I mean is that as consul's registration support http with json format, and don't need to do some stuff in this project again......thx@martin-helmich

Sorry, what? I honestly don't understand what you mean, at all. 😕 In any case, this issue was about ingesting JSON log data, not about the configuration settings. If you are suggesting a change in the configuration file format (?), please open a new issue (and elaborate a bit, please 😉).

**Comment by brandery** [comment]
ok. sorry for that. yes, I'm talking about config file format(consul&nbsp;config's separation).




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Martin Helmich"<notifications@github.com&gt;; 
发送时间: 2020年5月7日(星期四) 晚上9:30
收件人: "martin-helmich/prometheus-nginxlog-exporter"<prometheus-nginxlog-exporter@noreply.github.com&gt;; 
抄送: "AWSA_Brandrey"<1097174341@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [martin-helmich/prometheus-nginxlog-exporter] JSON File Support (#93)





  
how about separate the consul's config to a standalone file? which I mean is that as consul's registration support http with json format, and don't need to do some stuff in this project again......thx@martin-helmich
  
Sorry, what? I honestly don't understand what you mean, at all.  In any case, this issue was about ingesting JSON log data, not about the configuration settings. If you are suggesting a change in the configuration file format (?), please open a new issue (and elaborate a bit, please ).

**Comment by martin-helmich** [comment]
This should not have been closed. Still happy to accept PRs for this one.

**Comment by yngwiewang** [comment]
Hello, @martin-helmich. I'm facing this problem. Our Nginx prints log in json format so that it's convenient to collect the log file by filebeat and inject it into ES. When using the exporter, I print another log in plain text format. It's a little bit verbose. I want to do this job to support json format logs. I think for extensibility, we'd better make the parser an interface having different implementations, for now they are textparser and jsonparser. What's your opinion? Could I do the job?

**Comment by yngwiewang** [comment]
I have finished writing the code. I add a parser package, define an `Parser` interface and two implementations `TextParser` and `JsonParser`. I add a new `NamespaceConfig` options named Parser, it is assigned by a new “-parse” flag. I try to minimize the number of changed lines and keep backward compatibility. Can we ship go version in the dockerfile to 1.13+? I want to use wrapping errors. If you think the design is OK, I will open a PR. 

package parser
```go
// Parser parses a line of log as a map[string]string.
type Parser interface {
	ParseString(line string) (map[string]string, error)
}

// NewParser returns a Parser with the given config.NamespaceConfig
func NewParser(nsCfg config.NamespaceConfig) Parser {
	switch nsCfg.Parser {
	case "text":
		return textparser.NewTextParser(nsCfg.Format)
	case "json":
		return jsonparser.NewJsonParser()
	default:
		return textparser.NewTextParser(nsCfg.Format)
	}
}
```

package textparser
```go
/ TextParser parses variables patterns using config.NamespaceConfig.Format.
type TextParser struct {
	format string
}

// NewTextParser returns a new text parser.
func NewTextParser(format string) *TextParser {
	return &TextParser{
		format: format,
	}
}

// ParseString implements the Parser interface.
func (t *TextParser) ParseString(line string) (map[string]string, error) {
	parser := gonx.NewParser(t.format)
	entry, err := parser.ParseString(line)
	if err != nil {
		return nil, fmt.Errorf("text log parsing err: %w", err)
	}

	return entry.Fields(), nil
}
```

package jsonparser
```go
// JsonParser parses variables patterns using config.NamespaceConfig.Format.
type JsonParser struct{}

// NewTextParser returns a new json parser.
func NewJsonParser() *JsonParser {
	return &JsonParser{}
}

// ParseString implements the Parser interface.
// Values of the map may not be a string, so it needs to be converted.
func (j *JsonParser) ParseString(line string) (map[string]string, error) {
	var parsed map[string]interface{}
	err := json.Unmarshal([]byte(line), &parsed)
	if err != nil {
		return nil, fmt.Errorf("json log parsing err: %w", err)
	}

	fields := make(map[string]string, len(parsed))
	for k, v := range parsed {
		fields[k] = fmt.Sprintf("%v", v)
	}
	return fields, nil
}
```

**Comment by martin-helmich** [comment]
Hey @yngwiewang! :wave: Thanks for your work on this, I really like the design. You're welcome to open a PR for this change, and we'll get it merged. And yes, wrapping errors seems like a sensible idea to me as well, and I'd be fine with bumping the Go version. :+1:

**Comment by yngwiewang** [comment]
Hi, @martin-helmich! 😃Thank you for your approval, it really encouraged me. I have open a PR, please review it. Expecting it to be merged. I optimized the TestParser struct and did a benchmark, TestParser is about twice faster than JsonParser. If we can restrict the data type of the log field, we could use easyjson to make the JsonParser faster. Maybe we can discuss this issue later, please let me know if you have any opinion regarding this. I'm documenting the JSON parser function in the README file, it will take a few days.
